### ISSUE TITLE
Not Recognizing Ionic Tags

### ISSUE THREAD

**Issue by queejie** [bodiam/idea-ionic#1]
Thank you, Erik, for creating this plugin.  I've installed it, but it isn't recognizing the ionic tags.  I used a straight install of the ionic base platform.  Any ideas on what I might need to do to get it working?  Thanks in advance.

**Comment by bodiam** [comment]
Hi David,

Thanks for the feedback. At the moment, it's a 0.1 version, and doesn't
support this yet. Contributions welcome!

Erik

On Fri, Mar 6, 2015 at 4:40 PM, David Quinn-Jacobs <notifications@github.com

**Comment by queejie** [comment]
Okay, thanks for the quick response!  If I can figure out how plugin code works I'll see if I can add anything! :)

**Comment by bodiam** [comment]
Right now it's only templates, so if you want, I'd appreciate some
contributions on that. I used this page:
ionicframework.com/docs/components/#header, and started from top to bottom.
All templates are generated by running a Groovy script, to make adding
templates much easier. Any contributions to that would be most appreciated!

On Fri, Mar 6, 2015 at 5:15 PM, David Quinn-Jacobs <notifications@github.com
