### ISSUE TITLE
Can't seem to get plugin to work

### ISSUE THREAD

**Issue by iangregsondev** [bodiam/idea-ionic#2]

**Comment by bodiam** [comment]
It's fixed?

**Comment by iangregsondev** [comment]
Yes, sorry, my fault. Its working as expected. I was a little too quick on the issue writing :-)

Thanks

**Comment by bodiam** [comment]
Nothing wrong with a bit of rubberducking ;-). Btw, the plugin is quite limited btw, so if you feel inclined to add some templates, I'd be very willing to accept any pull requests!
